Replace the named drs uris with numbered drs uris.

In [38]:
import sqlite3
db_name = "../ga4gh-starter-kit.dev.db"
connection = sqlite3.connect(db_name)

In [17]:
import json

with open("../drs_map.json") as f:
    drs_map = json.load(f)

In [31]:
def fix_row(line):
    key_list = ['cram_drs_uri', 'crai_drs_uri', 'bundle_drs_uri']
    sample = json.loads(line)
    for k in key_list:
        # get the part after the last /
        drs_id = sample[k].split('/')[-1]
        sample[k] =  f"drs://localhost:5000/{drs_map[drs_id]}"
    #print(json.dumps(sample, indent=3))
    return sample

In [39]:
cursor = connection.cursor()
rows = cursor.execute(
    "SELECT id, json_data FROM one_thousand_genomes_sample WHERE id > 5",

).fetchall()
id = str(rows[0][0])
print(rows[0][1])

{"sample_name": "NA18633", "sex": "male", "biosample_id": "SAME124704", "population_code": "CHB", "population_name": "Han Chinese", "superpopulation_code": "EAS", "superpopulation_name": "East Asian Ancestry", "population_elastic_id": "CHB", "data_collections": "1000 Genomes on GRCh38,1000 Genomes 30x on GRCh38,1000 Genomes phase 3 release,1000 Genomes phase 1 release,90 Han Chinese high coverage genomes", "cram_drs_uri": "drs://localhost:5000/0a9f0c4eeb7af0b6ed68818bef8eeed6", "crai_drs_uri": "drs://localhost:5000/fc874aaf8ca1ddb3d07f7a93dc7f3ee7", "bundle_drs_uri": "drs://localhost:5000/f9bfdfef4066fa94bc10a14ac83e71ae"}

In [35]:
for r in rows:
    id =str(r[0])
    new_json = fix_row(r[1])
    #print(new_json)
    jstring = json.dumps(new_json)
    #print(jstring)
    cursor.execute(
    "UPDATE one_thousand_genomes_sample SET json_data = ? WHERE id = ?",
    (jstring,id))
    connection.commit()
    print(id)

6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200

In [45]:
from contextlib import closing

with closing(sqlite3.connect(db_name)) as connection:
    with closing(connection.cursor()) as cursor:
        rows = cursor.execute("SELECT 1").fetchall()
        print(rows)

[(1,)]